#!/usr/bin/env python3
"""
parse_flowmon.py - ns-3 FlowMonitor XML Parser
Version: 1.0.0

Parses XML files generated by FlowMonitor::SerializeToXmlFile() in ns-3 simulations.
Extracts per-flow statistics: packet counts, data volumes, packet loss ratio, and delay metrics.

Usage:
  python3 parse_flowmon.py lte-flowmon.xml
  python3 parse_flowmon.py --help
  python3 parse_flowmon.py --version
"""

import xml.etree.ElementTree as ET
import argparse
import sys

__version__ = "1.0.0"

def parse_args():
    parser = argparse.ArgumentParser(
        description="Parse ns-3 FlowMonitor XML output (generated by monitor->SerializeToXmlFile()). "
                    "Extracts and displays per-flow statistics including packet counts, data volumes, "
                    "packet loss ratio, and delay/jitter metrics.",
        epilog="Example: python3 parse_flowmon.py lte-flowmon.xml"
    )
    parser.add_argument("xml_file", help="Path to the FlowMonitor XML file (e.g., lte-flowmon.xml)")
    parser.add_argument("-v", "--version", action="version", version=f"%(prog)s {__version__}")
    return parser.parse_args()

def parse_ns3_time(time_str):
    """Converts ns-3 time string (e.g., '+2.02143e+07ns') to nanoseconds (float)."""
    if not time_str:
        return 0.0
    clean = time_str.strip('+').replace('ns', '')
    try:
        return float(clean)
    except ValueError:
        return 0.0

def safe_float(val, default=0.0):
    try:
        return float(val) if val is not None else default
    except (ValueError, TypeError):
        return default

def safe_int(val, default=0):
    try:
        return int(val) if val is not None else default
    except (ValueError, TypeError):
        return default

def safe_str(val, default="N/A"):
    return val if val else default

def main():
    args = parse_args()
    xml_file = args.xml_file

    try:
        tree = ET.parse(xml_file)
        root = tree.getroot()
    except FileNotFoundError:
        print(f"Error: File '{xml_file}' not found.", file=sys.stderr)
        sys.exit(1)
    except ET.ParseError as e:
        print(f"Error: Invalid XML format - {e}", file=sys.stderr)
        sys.exit(1)

    # 1️⃣ Extract addresses from Ipv4FlowClassifier (ns-3 stores IPs separately from stats)
    flow_addresses = {}
    classifier = root.find('Ipv4FlowClassifier')
    if classifier is not None:
        for flow in classifier.findall('Flow'):
            fid = flow.get('flowId')
            if fid:
                flow_addresses[fid] = {
                    'src': safe_str(flow.get('sourceAddress')),
                    'dst': safe_str(flow.get('destinationAddress')),
                    'srcPort': safe_str(flow.get('sourcePort')),
                    'dstPort': safe_str(flow.get('destinationPort')),
                    'proto': safe_str(flow.get('protocol'))
                }

    # 2️⃣ Parse FlowStats
    flow_stats = root.find('FlowStats')
    if flow_stats is None:
        print("Error: No <FlowStats> section found in XML.", file=sys.stderr)
        sys.exit(1)

    # 📊 Table Header
    header = (f"{'FlowID':<7} {'Src:Port':<20} {'Dst:Port':<20} "
              f"{'TxPkt':<6} {'RxPkt':<6} {'Lost':<5} "
              f"{'Tx(MB)':<8} {'Rx(MB)':<8} {'Loss%':<7} {'Delay(ns)':<12}")
    print(header)
    print("-" * len(header))

    # 🔢 Accumulators for summary
    total_tx_pkt = 0
    total_rx_pkt = 0
    total_lost_pkt = 0
    total_tx_bytes = 0.0
    total_rx_bytes = 0.0

    for flow in flow_stats.findall('Flow'):
        fid = safe_str(flow.get('flowId'), '?')
        addr_info = flow_addresses.get(fid, {})

        src = addr_info.get('src', '?')
        dst = addr_info.get('dst', '?')
        src_port = addr_info.get('srcPort', '?')
        dst_port = addr_info.get('dstPort', '?')

        # 📦 Packet & byte metrics
        tx_pkts = safe_int(flow.get('txPackets'))
        rx_pkts = safe_int(flow.get('rxPackets'))
        lost_pkts = safe_int(flow.get('lostPackets'))
        tx_bytes = safe_float(flow.get('txBytes'))
        rx_bytes = safe_float(flow.get('rxBytes'))

        # ⏱ Delay calculation
        delay_sum_ns = parse_ns3_time(flow.get('delaySum'))
        avg_delay_ns = delay_sum_ns / rx_pkts if rx_pkts > 0 else 0.0

        # 📈 Derived metrics
        tx_mb = tx_bytes / 1e6
        rx_mb = rx_bytes / 1e6
        loss_pct = (lost_pkts / tx_pkts * 100) if tx_pkts > 0 else 0.0

        # 📊 Accumulate totals
        total_tx_pkt += tx_pkts
        total_rx_pkt += rx_pkts
        total_lost_pkt += lost_pkts
        total_tx_bytes += tx_bytes
        total_rx_bytes += rx_bytes

        # 🖨 Print row
        src_full = f"{src}:{src_port}"
        dst_full = f"{dst}:{dst_port}"
        print(f"{fid:<7} {src_full:<20} {dst_full:<20} {tx_pkts:<6} {rx_pkts:<6} "
              f"{lost_pkts:<5} {tx_mb:<8.3f} {rx_mb:<8.3f} {loss_pct:<7.2f} {avg_delay_ns:<12.1f}")

    # 📋 Summary block
    print("\n" + "=" * len(header))
    print("SUMMARY")
    print("=" * len(header))
    total_loss_pct = (total_lost_pkt / total_tx_pkt * 100) if total_tx_pkt > 0 else 0.0
    print(f"Total Packets: Tx={total_tx_pkt} | Rx={total_rx_pkt} | Lost={total_lost_pkt} ({total_loss_pct:.2f}%)")
    print(f"Total Data:    Tx={total_tx_bytes/1e6:.3f} MB | Rx={total_rx_bytes/1e6:.3f} MB")

if __name__ == "__main__":
    main()
